### ISSUE TITLE
Problem with requesting json

### ISSUE THREAD

**Issue by jdlrobson** [tiddlyweb/tiddlywebplugins.links#3]
I recently threw a 500 error on TiddlySpace when visiting this url:

http://jon.tiddlyspace.com/bags/jon_public/tiddlers/plugin%20meta%20markup%20for%20tiddlywiki/backlinks.json

This may be due to the latest changes to deal with issue #1.

The stack trace was

```
There was a 500 server error error with the following message:

500 server error: Traceback (most recent call last): File "/usr/lib/python2.5/site-packages/tiddlywebplugins/prettyerror/exceptor.py", line 56, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/wsgi.py", line 258, in __call__ output = self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/wsgi.py", line 47, in __call__ output = self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/serve.py", line 113, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/serve.py", line 98, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/methodhack.py", line 55, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/query.py", line 27, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/pathinfohack.py", line 40, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/wsgi.py", line 218, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/extractor.py", line 30, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/tiddlyspace/controlview.py", line 62, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/tiddlyspace/controlview.py", line 151, in __call__ output = self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/wsgi.py", line 33, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/negotiate.py", line 25, in __call__ return self.application(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/etagcache.py", line 65, in __call__ output = self.application(environ, replacement_start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/tiddlyspace/csrf.py", line 60, in __call__ return app() File "/usr/lib/python2.5/site-packages/tiddlywebplugins/tiddlyspace/csrf.py", line 56, in app output = self.application(environ, fake_start_response) File "/usr/lib/python2.5/site-packages/selector.py", line 161, in __call__ return app(environ, start_response) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/links/__init__.py", line 75, in get_backlinks return _get_links(environ, start_response, 'backlinks') File "/usr/lib/python2.5/site-packages/tiddlywebplugins/links/__init__.py", line 154, in _get_links return send_tiddlers(environ, start_response, tiddlers=tiddlers) File "/usr/lib/python2.5/site-packages/tiddlyweb/web/sendtiddlers.py", line 70, in send_tiddlers output = serializer.list_tiddlers(candidate_tiddlers) File "/usr/lib/python2.5/site-packages/tiddlyweb/serializer.py", line 116, in list_tiddlers return self.serialization.list_tiddlers(tiddlers) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/jsonp.py", line 39, in list_tiddlers return prefix + JSON.list_tiddlers(self, bag) + suffix File "/usr/lib/python2.5/site-packages/tiddlyweb/serializations/json.py", line 47, in list_tiddlers tiddler in tiddlers]) File "/usr/lib/python2.5/site-packages/tiddlyweb/serializations/json.py", line 152, in _tiddler_dict wanted_info['permissions'] = self._tiddler_permissions(tiddler) File "/usr/lib/python2.5/site-packages/tiddlyweb/serializations/json.py", line 193, in _tiddler_permissions perms = _read_bag_perms(self.environ, tiddler) File "/usr/lib/python2.5/site-packages/tiddlyweb/serializations/json.py", line 179, in _read_bag_perms bag = store.get(bag) File "/usr/lib/python2.5/site-packages/tiddlyweb/store.py", line 161, in get thing = func(thing) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/caching.py", line 169, in bag_get bag = self.cached_storage.bag_get(bag) File "/usr/lib/python2.5/site-packages/tiddlywebplugins/sqlalchemy2/__init__.py", line 495, in bag_get raise NoBagError('Bag %s not found: %s' % (bag.name, exc)) NoBagError: Bag temp not found: No row was found for one()
```

**Comment by cdent** [comment]
this turned out to be a problem in the json serialization, i've fixed it there: https://github.com/tiddlyweb/tiddlyweb/commit/f984461bd4d5be56be6d3b37121632610b688f23
